services:
  postgres:
    image: postgres:15-alpine
    container_name: budget_postgres
    environment:
      POSTGRES_DB: budget_db
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - budget_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: budget_web
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: budget_db
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password_2025
      POSTGRES_PORT: 5432
      FLASK_SECRET_KEY: docker-secret-key-budget-app-2025
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./src/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - budget_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  budget_network:
    driver: bridge
